### ISSUE TITLE
Fail to load `mkdocs.yml`

### ISSUE THREAD

**Issue by ThibsG** [ovasquez/mkdocs-merge#15]
Hi @ovasquez , thank you for this useful tool!

I encounter an issue when in my `mkdocs.yml` of a sub-site I'm using special characters, such as `!`:

```yaml
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
```
for example when you setup this extension: https://github.com/facelessuser/mkdocs-material-extensions#inline-svg-icons

turns into:

```console
❯ mkdocs-merge run master_site sub_site

Attempting to merge site: sub_site
Error loading the yaml file "sub_site/mkdocs.yml". This site will be skipped.
```

Sounds like the Ruamel Yaml parser is not working with such `!!` tag
