### ISSUE TITLE
Add support for section index pages

### ISSUE THREAD

**Issue by Acerinth** [ovasquez/mkdocs-merge#17]
Hey there!

Firstly, thank you so much for this amazing tool!

In our company, we use it in combo with [MkDocs Material](https://squidfunk.github.io/mkdocs-material/). Not sure about original MkDocs, but in this version, there is an option to set index pages for sections. To get a better understanding, please take a look at [feature description](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages).

It's very simple, and what it means, is that basically you may now have a nav entry in `mkdocs.yml` that looks like this:
```yaml
nav:
  - Home: index.md
  - Section:
    - section/index.md                             #   <--- this right here is new!
    - Page 1: section/page-1.md
    ...
    - Page n: section/page-n.md
```

Those kind of entries are currently not supported and result in "Error merging the "nav" entry in the site:   xxxx".

I've taken a quick look at the code - to me seems like a new elif in recursive function `update_navs` should be added where `nav` can be instance of `str`, or sth like that. 

I hope you'll have a bit of time to consider this.

Thanks!
